### ISSUE TITLE
Mettre en cache les pages

### ISSUE THREAD

**Issue by MattiSG** [betagouv/mes-aides-ops#26]
En tant qu'utilisateur,
Je ne subis pas d'interruption de service même en cas de pic de charge,
Pour accéder au service quand le journal télévisé en parle

**Comment by guillett** [comment]
Les pages son intégrées dans les bundles JS suffixés, non supprimés en redéploiement et servies en direct par NGINX. Cette configuration devrait tenir le coup en cas de passage à la télé. Je ferme.
