### ISSUE TITLE
Corriger l'horloge du serveur

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ops#91]
Lancé en local :
```
ssh root@mes-aides.gouv.fr date && date
Tue Feb 19 19:11:52 CET 2019
mardi 19 février 2019, 18:55:18 (UTC+0100)
```

Un écart de plusieurs minutes existent entre le serveur et ma machine. Ma machine est à l'heure. Des écarts d'horloge peuvent générer des erreurs bizarres que l'on pourrait éviter.

**Comment by alexsegura** [comment]
https://forge.puppet.com/puppetlabs/ntp ?

**Comment by guillett** [comment]
Ouais carrément.
